apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
spec: 
  containers:
   - name: todo-app-gitops
     image: chetankumar01/todo-app-gitops:9e65de39b3f1e12c3a67a027d316bd45e69b2e31
     ports:
       - containerPort: 3000
