apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
spec: 
  containers:
   - name: todo-app-gitops
     image: chetankumar01/todo-app-gitops:4b17f948a0488d5f48bcb7cdb4d806625225cc56
     ports:
       - containerPort: 3000
